### PR TITLE
Send the githubToken to actionutils to use authenticated calls to github when looking for packages

### LINKED ISSUE #32: Unauthenticated access warning even though github_token is specified
Seeing rate limits due to being unauthenticated when running the install-action github action. We do have github-token set as mentioned though: 

Screenshot 2023-12-18 at 17 35 55

Screenshot 2023-12-18 at 17 35 09

### PR DESCRIPTION
**Pull request by petecheslock**
Looking at this code when we search for the AppMap releases in Github, it appears we are not sending the githubToken to actionutils?  https://github.com/getappmap/action-utils/blob/main/src/installAppMapTools.ts#L27

I have some test builds where the rate limit for unauthenticated requests decreases after installing the action but the authenticated requests don't decrease which makes me think the issue is that when we search for the binary to install we're not making an authenticated call to search for the binary.  

here are 2 example builds where you can see the rate limit change for unauthenticated API calls
https://github.com/land-of-apps/rails-7-app/actions/runs/7266433552/job/19798166764
https://github.com/land-of-apps/rails-7-app/actions/runs/7266542030/job/19798969998

Going to test this branch on a build to see if this changes the API rate limit counters. 

Fixes #32

### CODE REVIEW

**Comment by petecheslock** [comment]
Ok - on this run the rate limit counters for authenticated API requests went down while unauthenticated requests stayed the same.  So i think this works and is ready for review.

https://github.com/land-of-apps/rails-7-app/actions/runs/7267822180/job/19802437171

**Comment by petecheslock** [comment]
With the token explicitly set as well you can see the authenticated counters going down after install.   

https://github.com/land-of-apps/rails-7-app/actions/runs/7277894754/job/19830914021

**Review by kgilpin — APPROVED** [review]
Good catch! Is there anywhere else might need to do this?

**Comment by petecheslock** [comment]
Oh good thinking @kgilpin i can check the other actions and make sure we are not missing this as well.

**Pull request merged**
